[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FIGlet = "3064a664-84fe-4d92-92c7-ed492f3d8fae"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
PDFIO = "4d0d745f-9d9a-592e-8d18-1ad8a0f42b92"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
